package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"
)

func Generate(root string) error {
	project, err := loadProject(root)
	if err != nil {
		return err
	}
	catalog, err := loadModels(project.modelPath, project.module)
	if err != nil {
		return err
	}
	spec, err := loadSpecFile(project.specPath)
	if err != nil {
		return fmt.Errorf("load OpenAPI contract: %w", err)
	}
	if err := syncModelSchemas(spec, catalog); err != nil {
		return err
	}
	contract, err := marshalAndValidate(spec)
	if err != nil {
		return err
	}

	validated, err := loadSpecData(contract)
	if err != nil {
		return err
	}
	generated, err := codegen.Generate(validated, codegen.Configuration{
		PackageName: "httpgen",
		Generate: codegen.GenerateOptions{
			Models:        true,
			StdHTTPServer: true,
			Client:        true,
		},
	})
	if err != nil {
		return fmt.Errorf("generate OpenAPI Go code: %w", err)
	}
	apiSource, err := format.Source([]byte(generated))
	if err != nil {
		return fmt.Errorf("format generated OpenAPI code: %w", err)
	}
	operations, err := operationsFromSpec(validated)
	if err != nil {
		return err
	}
	routesSource, err := renderRoutes(project.module, operations)
	if err != nil {
		return err
	}

	if err := writeManaged(filepath.Join(project.root, filepath.FromSlash(GeneratedDir), "api.gen.go"), apiSource); err != nil {
		return err
	}
	if err := writeManaged(filepath.Join(project.root, "internal", "transport", "http", "routes.gen.go"), routesSource); err != nil {
		return err
	}
	if err := atomicWrite(project.specPath, contract); err != nil {
		return err
	}
	return nil
}

func loadSpecData(contents []byte) (*openapi3.T, error) {
	loader := openapi3.NewLoader()
	spec, err := loader.LoadFromData(contents)
	if err != nil {
		return nil, fmt.Errorf("reload OpenAPI contract: %w", err)
	}
	return spec, nil
}

func operationsFromSpec(spec *openapi3.T) ([]Operation, error) {
	var operations []Operation
	if spec.Paths == nil {
		return operations, nil
	}
	paths := make([]string, 0, spec.Paths.Len())
	for path := range spec.Paths.Map() {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		item := spec.Paths.Value(path)
		methods := make([]string, 0, len(item.Operations()))
		for method := range item.Operations() {
			methods = append(methods, method)
		}
		sort.Strings(methods)
		for _, method := range methods {
			contract := item.GetOperation(method)
			metadata, exists := contract.Extensions[operationExtension]
			if !exists {
				return nil, fmt.Errorf("%w: operation %s lacks %s metadata; add it with jgo api add", ErrInvalidOperation, contract.OperationID, operationExtension)
			}
			operation, err := decodeOperationMetadata(metadata)
			if err != nil {
				return nil, fmt.Errorf("operation %s: %w", contract.OperationID, err)
			}
			operation.Name = contract.OperationID
			operation.Method = strings.ToUpper(method)
			operation.Path = path
			operations = append(operations, operation)
		}
	}
	return operations, nil
}

func decodeOperationMetadata(value any) (Operation, error) {
	contents, err := json.Marshal(value)
	if err != nil {
		return Operation{}, fmt.Errorf("decode JGO metadata: %w", err)
	}
	var raw struct {
		RequestType  string `json:"requestType"`
		ResponseType string `json:"responseType"`
		ResponseList bool   `json:"responseList"`
		Fields       []struct {
			Name     string `json:"name"`
			GoName   string `json:"goName"`
			GoType   string `json:"goType"`
			Source   string `json:"source"`
			Required bool   `json:"required"`
		} `json:"fields"`
	}
	if err := json.Unmarshal(contents, &raw); err != nil {
		return Operation{}, fmt.Errorf("decode JGO metadata: %w", err)
	}
	operation := Operation{
		RequestType: raw.RequestType, ResponseType: raw.ResponseType, ResponseList: raw.ResponseList,
	}
	for _, field := range raw.Fields {
		operation.Fields = append(operation.Fields, Field{
			Name: field.Name, GoName: field.GoName, GoType: field.GoType,
			Source: field.Source, Required: field.Required,
		})
	}
	return operation, nil
}

func renderRoutes(modulePath string, operations []Operation) ([]byte, error) {
	if len(operations) == 0 {
		return format.Source([]byte(`package httptransport

import (
	"net/http"

	"` + modulePath + `/internal/service"
)

func registerGeneratedRoutes(mux *http.ServeMux, application *service.Service) {
	_ = mux
	_ = application
}
`))
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by jgo api generate. DO NOT EDIT.\n")
	output.WriteString("package httptransport\n\n")
	imports := []string{
		"\"net/http\"",
		"jerrors \"github.com/eyesofblue/jgo/errors\"",
		"\"github.com/eyesofblue/jgo/response\"",
		fmt.Sprintf("httpgen %q", modulePath+"/"+GeneratedDir),
		fmt.Sprintf("%q", modulePath+"/internal/service"),
	}
	needsModel := false
	needsJSON := false
	for _, operation := range operations {
		if operation.RequestType != "" {
			needsModel = true
			needsJSON = true
		}
		for _, field := range operation.Fields {
			if field.Source == "body" {
				needsJSON = true
			}
		}
	}
	if needsJSON {
		imports = append(imports, "\"encoding/json\"")
	}
	if needsModel {
		imports = append(imports, fmt.Sprintf("%q", modulePath+"/"+ModelPath))
	}
	sort.Strings(imports)
	output.WriteString("import (\n\t" + strings.Join(imports, "\n\t") + "\n)\n\n")
	output.WriteString("type generatedHandler struct {\n\tapplication *service.Service\n}\n\n")
	output.WriteString("func registerGeneratedRoutes(mux *http.ServeMux, application *service.Service) {\n")
	output.WriteString("\thandler := &generatedHandler{application: application}\n")
	output.WriteString("\thttpgen.HandlerWithOptions(handler, httpgen.StdHTTPServerOptions{\n")
	output.WriteString("\t\tBaseRouter: mux,\n")
	output.WriteString("\t\tErrorHandlerFunc: func(writer http.ResponseWriter, request *http.Request, err error) {\n")
	output.WriteString("\t\t\t_ = response.Error(writer, request, jerrors.Wrap(err, jerrors.CodeInvalidArgument, \"invalid request\", jerrors.WithHTTPStatus(http.StatusBadRequest)))\n")
	output.WriteString("\t\t},\n\t})\n}\n\n")
	for _, operation := range operations {
		renderRouteMethod(&output, operation)
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated HTTP transport: %w\n%s", err, output.String())
	}
	return formatted, nil
}

func renderRouteMethod(output *bytes.Buffer, operation Operation) {
	hasParams := false
	for _, field := range operation.Fields {
		if field.Source != "body" {
			hasParams = true
		}
	}
	fmt.Fprintf(output, "func (handler *generatedHandler) %s(writer http.ResponseWriter, request *http.Request", operation.Name)
	if hasParams {
		fmt.Fprintf(output, ", params httpgen.%sParams", operation.Name)
	}
	output.WriteString(") {\n")
	if operation.HasRequest() {
		requestType := operation.ServiceRequestType()
		if operation.RequestType == "" {
			requestType = "service." + requestType
		}
		fmt.Fprintf(output, "\tvar input %s\n", requestType)
		if operation.RequestType != "" {
			fmt.Fprintf(output, "\tvar body model.%s\n", operation.RequestType)
			output.WriteString("\tif err := json.NewDecoder(request.Body).Decode(&body); err != nil {\n")
			output.WriteString("\t\t_ = response.Error(writer, request, jerrors.Wrap(err, jerrors.CodeInvalidArgument, \"invalid JSON body\", jerrors.WithHTTPStatus(http.StatusBadRequest)))\n\t\treturn\n\t}\n")
			output.WriteString("\tinput = body\n")
		} else {
			bodyFields := false
			for _, field := range operation.Fields {
				if field.Source == "body" {
					bodyFields = true
					break
				}
			}
			if bodyFields {
				output.WriteString("\tif err := json.NewDecoder(request.Body).Decode(&input); err != nil {\n")
				output.WriteString("\t\t_ = response.Error(writer, request, jerrors.Wrap(err, jerrors.CodeInvalidArgument, \"invalid JSON body\", jerrors.WithHTTPStatus(http.StatusBadRequest)))\n\t\treturn\n\t}\n")
			}
			for _, field := range operation.Fields {
				if field.Source != "body" {
					fmt.Fprintf(output, "\tinput.%s = params.%s\n", field.GoName, field.GoName)
				}
			}
		}
	}
	responseType := operation.ServiceResponseType()
	if responseType == "" {
		if operation.HasRequest() {
			fmt.Fprintf(output, "\terr := handler.application.%s(request.Context(), input)\n", operation.Name)
		} else {
			fmt.Fprintf(output, "\terr := handler.application.%s(request.Context())\n", operation.Name)
		}
		output.WriteString("\tif err != nil {\n\t\t_ = response.Error(writer, request, err)\n\t\treturn\n\t}\n")
		output.WriteString("\t_ = response.Success(writer, request, nil)\n")
	} else {
		if operation.HasRequest() {
			fmt.Fprintf(output, "\tresult, err := handler.application.%s(request.Context(), input)\n", operation.Name)
		} else {
			fmt.Fprintf(output, "\tresult, err := handler.application.%s(request.Context())\n", operation.Name)
		}
		output.WriteString("\tif err != nil {\n\t\t_ = response.Error(writer, request, err)\n\t\treturn\n\t}\n")
		output.WriteString("\t_ = response.Success(writer, request, result)\n")
	}
	output.WriteString("}\n\n")
}

func writeManaged(path string, contents []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create generated directory: %w", err)
	}
	if _, err := os.Stat(path); err == nil {
		return atomicWrite(path, contents)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("inspect generated output: %w", err)
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".jgo-")
	if err != nil {
		return fmt.Errorf("create generated output: %w", err)
	}
	name := temporary.Name()
	defer os.Remove(name)
	if _, err := temporary.Write(contents); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("write generated output: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close generated output: %w", err)
	}
	if err := os.Rename(name, path); err != nil {
		return fmt.Errorf("commit generated output: %w", err)
	}
	return nil
}
