BUF_VERSION := 1.46.0
PROTOC_GEN_GO_VERSION := 1.36.7
PROTOC_GEN_GO_GRPC_VERSION := 1.5.1

.PHONY: fmt test vet build check doctor generate run tools api-generate rpc-generate

fmt:
	gofmt -w $$(find . -name '*.go' -not -path './vendor/*')

test:
	go test ./...

vet:
	go vet ./...

build:
	go build ./...

check: test vet build

doctor:
	jgo doctor

generate:
	jgo generate

run:
	go run ./cmd/server

tools:
	go install github.com/bufbuild/buf/cmd/buf@v$(BUF_VERSION)
	go install google.golang.org/protobuf/cmd/protoc-gen-go@v$(PROTOC_GEN_GO_VERSION)
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v$(PROTOC_GEN_GO_GRPC_VERSION)

api-generate:
	jgo api generate

rpc-generate:
	jgo rpc generate
