export GOTOOLCHAIN := local

.PHONY: fmt test vet build check doctor generate run tools api-generate pb-generate pb-lint

fmt:
	gofmt -w $$(find . -name '*.go' -not -path './vendor/*')

test:
	go test ./...

vet:
	go vet ./...

build:
	go build ./...

check: test vet build

doctor:
	jgo doctor

generate:
	jgo generate

run:
	go run ./cmd/server

tools:
	jgo tools install

api-generate:
	jgo api generate

pb-generate:
	jgo pb generate

pb-lint:
	jgo pb lint
