export GOTOOLCHAIN := local

.PHONY: fmt test vet build check doctor generate tools pb-lint pb-breaking

fmt:
	gofmt -w $$(find . -name '*.go' -not -path './vendor/*')

test:
	go test ./...

vet:
	go vet ./...

build:
	go build ./...

check: test vet build

doctor:
	jgo doctor

generate:
	jgo generate

tools:
	jgo tools install

pb-lint:
	jgo pb lint

pb-breaking:
	@echo 'usage: jgo pb breaking --against ''.git#branch=main'''
